language: node_js
node_js:
  - "11.6.0"
cache: npm
install: 
  - npm install
script:
  - npm run build 


after_success:
- npm run jestAndNotifyCoveralls

notifications:
    email:
      - promilbhardwaj.nith@gmail.com